#!/bin/bash
cd ..
if [ "$DOCKER_TAG" != "latest" ] ; then
  docker build --build-arg DOCKER_TAG=$DOCKER_TAG -f Docker/Dockerfile -t $IMAGE_NAME .
else
  docker build -f Docker/Dockerfile -t $IMAGE_NAME .
fi
